### ISSUE TITLE
custom_functions import from lib for code in pure python

### ISSUE THREAD

**Issue by CarolineMorton** [ebmdatalab/best_practice_guidance#1]
Hi @sebbacon 

I am making this first issue to see if this is a good format for this guidance. 

Let's discuss the custom_functions issue and what everyones thoughts. 

Thanks 
Caroline

**Comment by sebbacon** [comment]
So the thing I wanted to say was just the `custom_functions.py` may be unecessarily generic. If it's in `lib/` then that's probably enough of a standard; the module could be called something a bit more meaningful and could be split into several (e.g. `practice_descriptions.py`, `regression.py`, etc)

**Comment by CarolineMorton** [comment]
I have changed this
